--- Cargo.toml.orig	2023-10-11 17:14:12 UTC
+++ Cargo.toml
@@ -58,7 +58,7 @@ clircle = "0.4"
 semver = "1.0"
 path_abs = { version = "0.5", default-features = false }
 clircle = "0.4"
-bugreport = { version = "0.5.0", optional = true }
+bugreport = { version = "0.5.0", optional = true, default-features = false, features = ["git_hash", "format_markdown"]}
 etcetera = { version = "0.8.0", optional = true }
 grep-cli = { version = "0.1.9", optional = true }
 regex = { version = "1.8.3", optional = true }
