--- pyproject.toml.orig	2025-11-06 12:50:59 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=80", "setuptools-scm>=9.2.2"]
+requires = ["setuptools>=63", "setuptools-scm>=8"]
 build-backend = "setuptools.build_meta"
 
 [project]
